# Generated by Django 5.1.5 on 2025-02-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
    ]
