
services:
  web:
    build: .
    container_name: django2_python1
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  db:
    image: postgres:16-alpine
    container_name: django2_postgres
    restart: always
    environment:
      POSTGRES_DB: "django2"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty.123"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  rabbitmq:
    image: rabbitmq:3.13.7-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - 5672:5672
      - 15672:15672


volumes:
  postgres_data:
